### ISSUE TITLE
Error in main?

### ISSUE THREAD

**Issue by erlebach** [naveenjafer/BERT_Amazon_Reviews#1]
I restricted the training and testing to about 50,000 each for increased speed. Training proceeded fine on the GPU. Eval gave me an error suggesting that some data was not on the GPU. The

In the course of investigating, I came across the following function in main(): 

```
def saveEvalAndTrain(train, eval, config):
    val.to_csv("AMAZON-DATASET/Validations.csv")
    train.to_csv("AMAZON-DATASET/Train.csv")
```

My question si: shouldn't the argument be the variable "val", defined in main? I do not understand where this function is pulling "val" from and why this function even works. I do not know whether this helps with my problem or not, but this looks like an error. The function is called with "eval" as the second argument, and yet, "eval" is a function. It seems unlikely that this was the intention.

**Comment by naveenjafer** [comment]
Hi @erlebach . A series of fortunate enough typos have saved my grace. The val inside the saveEvalAndTrain function is the val from the __name__ == "__main__" entry point. Those variables are technically global in nature, so it worked out just fine in this case without throwing up any errors. But yes, I have made a typo with sending eval to the function, now that I think of it, val and train needn't even be sent to the function as params. The code does need a bit of refactoring.

**Comment by erlebach** [comment]
Hi again, 
Now that I have your attention, I'd like to report an exception I am getting on Ubuntu. As I said, I reduced the training and validation sets to about 5000 each to run some tests and to learn. Nice blog by the way. Training worked fine. I stopped the code once the model was written out. Then I ran in eval mode. Here is what happened: (the line numbers are somewhat different from your code since I added some print statements. 

The last line of the error message is: 
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_index_select

I do not see how that is possible. 

```
Traceback (most recent call last):
  File "main.py", line 193, in <module>
    val_acc, val_loss = evaluate(model, loss_func, val_loader, config)
  File "main.py", line 87, in evaluate
    logits = net(seq, attn_masks)
  File "/home/gerlebacher/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gerlebacher/src/BERT_Amazon_Reviews/classifier.py", line 28, in forward
    cont_reps, _ = self.bert_layer(seq, attention_mask = attn_masks)
  File "/home/gerlebacher/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gerlebacher/anaconda3/lib/python3.7/site-packages/transformers/modeling_bert.py", line 783, in forward
    input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
  File "/home/gerlebacher/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gerlebacher/anaconda3/lib/python3.7/site-packages/transformers/modeling_bert.py", line 173, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/home/gerlebacher/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gerlebacher/anaconda3/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/gerlebacher/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1725, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _th_index_select
```

**Comment by erlebach** [comment]
The error is fixed. There is no way you ran your code on the GPU. In main.py, you forgot to send your model to the GPU (see the line I added). Also, the first argument to classifier.SentimentClassifier(...) was 5 instead of num_classes. Your code would have failed if you for some reason changed the number of classes. 

        model = classifier.SentimentClassifier(num_classes, device, freeze_bert = False) 
        model.to(config["device"])

**Comment by naveenjafer** [comment]
Hi, yes the GPU compatible code is in the notebook attached to the repo.
I'm glad you were able to figure this out. I think this is mentioned
somewhere in the blog, if it wasn't, I should probably do it.

**Comment by lakdinesh** [comment]
I got on error NLL loss function 
ValueError: Expected input batch_size (0) to match target batch_size (32). 

Please help me to fix
